Append scss extension
matthewdavidson/node-sass-tilde-importer pull request #11
Opened 2019-01-22 14:57 UTC by kylekatarnls

Hi,

Here is what I had to do to be able to import scss files using a syntax like `~module-name/file` omitting `.scss` (for consistency with our other imports).

Even if (as far as I understand) it does not break existing features (full path and /index), it broke unit tests, could you please check if I did something wrong?

Thanks,

2019-01-22 16:32 UTC, kylekatarnls commented
I tried many things but don't succeed to make jest working with Node.js 4.

2019-01-23 16:20 UTC, kylekatarnls commented
@matthewdavidson @tadam313 I see 2 old PRs with no response, is this project abandoned?

2019-02-08 18:55 UTC, danoc commented
Would love to see this merged. Happy to help out if I can.

2019-02-08 20:45 UTC, kylekatarnls commented
I published it on npmjs.com, so you can require my fork meanwhile it's merged (if this project is not abandoned): `npm install --save @kylekatarnls/node-sass-tilde-importer`

2019-02-13 15:13 UTC, matthewdavidson requested changes
Apologies for taking so long to review this. Overall this seems like a reasonable feature and in line with existing scss file resolution behaviour. Some small things to fix since I did some housekeeping, but otherwise LGTM.

2019-02-13 15:13 UTC, matthewdavidson commented on index.test.js
> +  test('should support directory imports', function() {
```suggestion
  test('should support file imports minus extension', function() {
```

2019-02-13 15:25 UTC, kylekatarnls commented
Glad to hear! Changes applied.

2019-02-13 16:14 UTC, matthewdavidson approved these changes

2019-02-13 16:14 UTC, merged

2019-02-13 16:22 UTC, matthewdavidson commented
Again, thanks @kylekatarnls 👏 

Released as an alpha as I don't actively use this module anymore so I'll rely on feedback from you folk before 2.0.0 release. Also gives us a chance to add more features in the mean time.

2019-08-27 21:37 UTC, danoc commented
@matthewdavidson — I've verified that that `v2.0.0-alpha.1` fixes the problem for us. Would love to see an official `2.0.0` release if there is no additional in-flight work. Happy to help if there's anything I can do. 🙇